import * as fs from 'fs';
import * as path from 'path';
import { z } from 'zod';

/**
 * Deployment configuration.
 *
 * This repository is public: real values live in git-ignored files
 * (`config/<env>.json`) or environment variables, never in source. Only
 * `config/config.example.json` is tracked, and it holds placeholders.
 */

const accountId = z.string().regex(/^\d{12}$/, 'must be a 12-digit AWS account id');
const region = z.string().regex(/^[a-z]{2}(-gov)?-[a-z]+-\d$/, 'must be an AWS region code, e.g. eu-west-2');
const metadataKey = z.string().regex(/^[A-Za-z][A-Za-z0-9_-]{0,62}$/, 'metadata keys: letters, digits, _ and -');

const chunkingSchema = z.discriminatedUnion('strategy', [
  z.object({
    strategy: z.literal('FIXED_SIZE'),
    maxTokens: z.number().int().min(20).max(8192).default(300),
    overlapPercentage: z.number().int().min(1).max(99).default(20),
  }),
  z.object({
    strategy: z.literal('SEMANTIC'),
    maxTokens: z.number().int().min(20).max(8192).default(300),
    bufferSize: z.number().int().min(0).max(1).default(0),
    breakpointPercentileThreshold: z.number().int().min(50).max(99).default(95),
  }),
  z.object({ strategy: z.literal('NONE') }),
]);

export const configSchema = z
  .object({
    /** Short lowercase name used to prefix the stack and resource tags. */
    projectName: z
      .string()
      .min(2)
      .max(31)
      .regex(/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/, 'lowercase letters and digits, single hyphens between words'),
    /** Environment name, e.g. dev / test / prod. */
    envName: z.string().max(16).regex(/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/),
    /** Optional: defaults to CDK_DEFAULT_ACCOUNT (from your AWS credentials). */
    account: accountId.optional(),
    /** Optional: defaults to CDK_DEFAULT_REGION. Confirm S3 Vectors + Bedrock KB availability first. */
    region: region.optional(),
    /** `retain` keeps data stores on stack deletion (use for prod). */
    removalPolicy: z.enum(['retain', 'destroy']).default('retain'),

    documents: z
      .object({
        /** Only objects under this prefix are indexed. Must end with '/'. */
        prefix: z.string().regex(/^[A-Za-z0-9!_.*'()\-/]+\/$/, 'must be a simple key prefix ending in /').default('documents/'),
        noncurrentVersionExpirationDays: z.number().int().min(1).max(3650).default(30),
        accessLogExpirationDays: z.number().int().min(1).max(3650).default(365),
        /**
         * IAM role/user ARNs allowed to write or delete documents. When set, every
         * other principal is denied (documents become trusted model context, so
         * write access is a prompt-injection path). Keep real ARNs in your
         * git-ignored config. Empty = rely on IAM alone.
         */
        writerPrincipalArns: z
          .array(z.string().regex(/^arn:aws[a-z-]*:(iam|sts)::\d{12}:(role|user|assumed-role)\/[\w+=,.@/*-]+$/, 'must be an IAM role/user ARN'))
          .max(20)
          .default([]),
      })
      .prefault({}),

    knowledgeBase: z
      .object({
        /** Bedrock embedding model id; must be enabled in the account/region. */
        embeddingModelId: z.string().min(1).default('amazon.titan-embed-text-v2:0'),
        embeddingDimensions: z.number().int().refine((n) => [256, 384, 512, 1024, 1536, 3072].includes(n), 'unsupported dimension').default(1024),
        distanceMetric: z.enum(['cosine', 'euclidean']).default('cosine'),
        chunking: chunkingSchema.default({ strategy: 'FIXED_SIZE', maxTokens: 300, overlapPercentage: 20 }),
        /** DELETE removes vectors when the data source is deleted. */
        dataDeletionPolicy: z.enum(['DELETE', 'RETAIN']).default('DELETE'),
      })
      .prefault({}),

    ingestion: z
      .object({
        /** Re-sync automatically when documents are created/deleted. */
        eventDriven: z.boolean().default(true),
        /** Debounce window: changes inside this window share one ingestion job. */
        batchWindowSeconds: z.number().int().min(0).max(300).default(60),
        /** How long a change waits before retrying when a job is already running. */
        retryDelaySeconds: z.number().int().min(60).max(3600).default(300),
        maxReceiveCount: z.number().int().min(1).max(50).default(12),
        /** Optional safety-net full sync, e.g. "rate(1 day)". */
        scheduleExpression: z.string().regex(/^(rate|cron)\(.+\)$/).optional(),
      })
      .prefault({}),

    api: z
      .object({
        /** Cognito hosted domain prefix (globally unique per region) used for the OAuth2 token endpoint. */
        cognitoDomainPrefix: z.string().regex(/^[a-z0-9](?:[a-z0-9-]{1,61}[a-z0-9])$/),
        /** OAuth2 resource server identifier; scopes become `<id>/retrieve` and `<id>/ask`. */
        resourceServerIdentifier: z.string().regex(/^[a-z][a-z0-9-]{1,63}$/).default('kb-api'),
        /** Machine-to-machine app clients. Secrets are generated by Cognito, never stored here. */
        clients: z
          .array(z.object({ name: z.string().regex(/^[a-z][a-z0-9-]{1,63}$/), scopes: z.array(z.enum(['retrieve', 'ask'])).min(1) }))
          .min(1)
          .default([{ name: 'default-agent', scopes: ['retrieve'] }]),
        accessTokenValidityMinutes: z.number().int().min(5).max(1440).default(60),
        throttleRateLimit: z.number().min(1).max(10000).default(10),
        throttleBurstLimit: z.number().int().min(1).max(5000).default(20),
        /** Hard cap on concurrent query Lambda executions (cost/abuse guard). 0 disables the cap. */
        reservedConcurrency: z.number().int().min(0).max(1000).default(10),
        maxQueryLength: z.number().int().min(16).max(8000).default(1000),
        maxResults: z.number().int().min(1).max(100).default(10),
        /** Metadata keys callers may filter on. Anything else is rejected. */
        allowedFilterKeys: z.array(metadataKey).max(20).default([]),
        /** TLS policy for the execute-api endpoint. */
        securityPolicy: z.enum(['TLS_1_2', 'SecurityPolicy_TLS13_1_2_2021_06', 'SecurityPolicy_TLS13_1_3_2025_09']).default('SecurityPolicy_TLS13_1_2_2021_06'),
        /**
         * Enable API Gateway execution logging. This sets the account-wide API Gateway
         * CloudWatch role, which may conflict with other stacks in the same account/region.
         */
        executionLogging: z.boolean().default(false),
        waf: z
          .object({
            enabled: z.boolean().default(true),
            /** Requests per 5 minutes per source IP. */
            rateLimitPer5Min: z.number().int().min(10).max(2_000_000_000).default(500),
          })
          .prefault({}),
      }),

    generation: z
      .object({
        /** Deploys POST /v1/ask (RetrieveAndGenerate). Retrieve-only is the default. */
        enabled: z.boolean().default(false),
        /** Foundation model id or cross-region inference profile id (e.g. "eu.<model-id>"). */
        modelId: z.string().regex(/^[a-z0-9.:-]+$/).optional(),
        /** True when modelId is an inference profile (required for many models outside us-east-1). */
        inferenceProfile: z.boolean().default(false),
        guardrailId: z.string().regex(/^[a-z0-9]+$/).optional(),
        guardrailVersion: z.string().regex(/^(DRAFT|\d+)$/).optional(),
      })
      .prefault({})
      .refine((g) => !g.enabled || !!g.modelId, { message: 'generation.modelId is required when generation.enabled is true' })
      .refine((g) => !g.guardrailId === !g.guardrailVersion, { message: 'guardrailId and guardrailVersion must be set together' }),

    network: z
      .object({
        /** Run Lambdas in isolated subnets and reach Bedrock via PrivateLink endpoints (no NAT). */
        enableVpc: z.boolean().default(false),
        vpcCidr: z.string().regex(/^\d{1,3}(\.\d{1,3}){3}\/(1[6-9]|2[0-4])$/).default('10.20.0.0/22'),
        maxAzs: z.number().int().min(2).max(3).default(2),
      })
      .prefault({}),

    observability: z
      .object({
        logRetentionDays: z.union([z.literal(1), z.literal(3), z.literal(5), z.literal(7), z.literal(14), z.literal(30), z.literal(60), z.literal(90), z.literal(120), z.literal(150), z.literal(180), z.literal(365), z.literal(400), z.literal(545), z.literal(731), z.literal(1827), z.literal(2192), z.literal(2557), z.literal(2922), z.literal(3288), z.literal(3653)]).default(90),
        /** Log query text and results. Leave false outside dev: queries may contain personal data. */
        logQueries: z.boolean().default(false),
        /** Optional email for alarm notifications (keep it in your git-ignored config). */
        alarmEmail: z.email().optional(),
      })
      .prefault({}),

    /** Extra tags applied to every resource (e.g. CostCentre, DataClassification). */
    tags: z.record(z.string().regex(/^[\w.:/=+\-@ ]{1,128}$/), z.string().max(256)).default({}),
  })
  .strict();

export type KbConfig = z.infer<typeof configSchema>;

export interface LoadedConfig extends KbConfig {
  account: string | undefined;
  region: string | undefined;
}

export interface LoadConfigOptions {
  /** Environment name selecting `config/<env>.json`. */
  envName?: string;
  /** Explicit path to a config file (overrides envName lookup). */
  configFile?: string;
  /** Environment variables (injected for testing). */
  env?: NodeJS.ProcessEnv;
  /** Directory containing config files. */
  configDir?: string;
}

/**
 * Load and validate configuration.
 *
 * Precedence (highest first): KB_* environment variables, config file,
 * schema defaults. Account/region fall back to CDK_DEFAULT_ACCOUNT/REGION.
 */
export function loadConfig(options: LoadConfigOptions = {}): LoadedConfig {
  const env = options.env ?? process.env;
  const configDir = options.configDir ?? path.join(__dirname, '..', 'config');
  const envName = options.envName ?? env.KB_ENV;
  const configFile = options.configFile ?? env.KB_CONFIG_FILE ?? (envName ? path.join(configDir, `${envName}.json`) : undefined);

  if (!configFile) {
    throw new Error('No configuration selected. Pass `-c env=<name>` (reads config/<name>.json), or set KB_ENV or KB_CONFIG_FILE. See config/config.example.json.');
  }
  if (!fs.existsSync(configFile)) {
    throw new Error(`Config file not found: ${configFile}. Copy config/config.example.json and fill in your values.`);
  }

  let raw: Record<string, unknown>;
  try {
    raw = JSON.parse(fs.readFileSync(configFile, 'utf8')) as Record<string, unknown>;
  } catch (e) {
    throw new Error(`Config file ${configFile} is not valid JSON: ${(e as Error).message}`, { cause: e });
  }
  // Strip documentation-only keys from the example template.
  delete raw.$comment;
  if (envName && raw.envName === undefined) raw.envName = envName;

  applyEnvOverrides(raw, env);

  const parsed = configSchema.safeParse(raw);
  if (!parsed.success) {
    const issues = parsed.error.issues.map((i) => `  - ${i.path.join('.') || '(root)'}: ${i.message}`).join('\n');
    throw new Error(`Invalid configuration in ${configFile}:\n${issues}`);
  }

  const account = parsed.data.account ?? env.CDK_DEFAULT_ACCOUNT;
  const region = parsed.data.region ?? env.CDK_DEFAULT_REGION;
  if (account !== undefined) accountId.parse(account);
  if (region !== undefined) regionCheck(region);

  return { ...parsed.data, account, region };
}

function regionCheck(value: string): void {
  const r = region.safeParse(value);
  if (!r.success) throw new Error(`Invalid region "${value}"`);
}

/** Selected values may be overridden from the environment (e.g. in CI). */
function applyEnvOverrides(raw: Record<string, unknown>, env: NodeJS.ProcessEnv): void {
  if (env.KB_ACCOUNT) raw.account = env.KB_ACCOUNT;
  if (env.KB_REGION) raw.region = env.KB_REGION;
  if (env.KB_ALARM_EMAIL) {
    raw.observability = { ...(raw.observability as object | undefined), alarmEmail: env.KB_ALARM_EMAIL };
  }
  if (env.KB_COGNITO_DOMAIN_PREFIX) {
    raw.api = { ...(raw.api as object | undefined), cognitoDomainPrefix: env.KB_COGNITO_DOMAIN_PREFIX };
  }
}
